# Generated by Django 2.1.4 on 2018-12-08 01:16

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(verbose_name='Date Added')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=cards.models.get_image_path)),
            ],
        ),
    ]
