# Generated by Django 2.1.4 on 2018-12-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.CharField(choices=[('original', 'ORIGINAL'), ('persephone', 'PERSEPHONE'), ('chimera', 'CHIMERA'), ('pandora', 'PANDORA'), ('odyssey', 'ODYSSEY')], default='original', max_length=10),
        ),
    ]
