# Generated by Django 2.1.4 on 2020-03-20 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_card_deck"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=30)),
                (
                    "deck",
                    models.CharField(
                        choices=[
                            ("original", "ORIGINAL"),
                            ("persephone", "PERSEPHONE"),
                            ("chimera", "CHIMERA"),
                            ("pandora", "PANDORA"),
                            ("odyssey", "ODYSSEY"),
                        ],
                        default="original",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="card",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cards.Deck"
            ),
        ),
    ]
