# Generated by Django 2.1.4 on 2020-03-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_deck_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card", old_name="identifier", new_name="card_name",
        ),
        migrations.RenameField(
            model_name="deck", old_name="identifier", new_name="deck_name",
        ),
    ]
