# Generated by Django 3.0.4 on 2020-03-27 17:38

import cards.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_rename_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='deck',
        ),
        migrations.AddField(
            model_name='deck',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=cards.utils.get_image_path),
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_name',
            field=models.CharField(choices=[(1, 'ORIGINAL'), (2, 'PERSEPHONE'), (3, 'CHIMERA'), (4, 'PANDORA'), (5, 'ODYSSEY')], default=1, max_length=10),
        ),
    ]
