# Generated by Django 3.0.4 on 2020-03-29 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_rename_deck_name_to_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='type',
            field=models.CharField(choices=[(1, 'ORIGINAL'), (2, 'PERSEPHONE'), (3, 'CHIMERA'), (4, 'PANDORA'), (5, 'ODYSSEY'), (6, 'ARIADNE')], default=1, max_length=10),
        ),
    ]
